<?php
/**
 * VersionBuildParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kleister
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kleister OpenAPI
 *
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Kleister;

use PHPUnit\Framework\TestCase;

/**
 * VersionBuildParamsTest Class Doc Comment
 *
 * @category    Class
 * @description VersionBuildParams
 * @package     Kleister
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VersionBuildParamsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VersionBuildParams"
     */
    public function testVersionBuildParams()
    {
    }

    /**
     * Test attribute "mod"
     */
    public function testPropertyMod()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "pack"
     */
    public function testPropertyPack()
    {
    }

    /**
     * Test attribute "build"
     */
    public function testPropertyBuild()
    {
    }
}
