<?php
/**
 * ProfileApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Kleister
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kleister OpenAPI
 *
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Kleister\Test\Api;

use \Kleister\Configuration;
use \Kleister\ApiException;
use \Kleister\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProfileApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kleister
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProfileApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for showProfile
     *
     * Retrieve an unlimited auth token.
     *
     */
    public function testShowProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenProfile
     *
     * Retrieve an unlimited auth token.
     *
     */
    public function testTokenProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProfile
     *
     * Retrieve an unlimited auth token.
     *
     */
    public function testUpdateProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
